In [30]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('C:\\Users\\User\\Documents\\GitHub\\incident_trend_root_cause_analysis\\Data\\incident_event_log.csv')
df

,number,incident_state,active,reassignment_count,reopen_count,sys_mod_count,made_sla,caller_id,opened_by,opened_at,...,u_priority_confirmation,notify,problem_id,rfc,vendor,caused_by,closed_code,resolved_by,resolved_at,closed_at
0,INC0000045,New,True,0,0,0,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
1,INC0000045,Resolved,True,0,0,2,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
2,INC0000045,Resolved,True,0,0,3,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
3,INC0000045,Closed,False,0,0,4,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
4,INC0000047,New,True,0,0,0,True,Caller 2403,Opened by 397,29/2/2016 04:40,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 81,1/3/2016 9:52,6/3/2016 10:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141707,INC0120835,Closed,False,1,0,4,True,Caller 116,Opened by 12,16/2/2017 09:09,...,True,Do Not Notify,?,?,?,?,code 9,Resolved by 9,16/2/2017 09:53,16/2/2017 09:53
141708,INC0121064,Active,True,0,0,0,True,Caller 116,Opened by 12,16/2/2017 14:17,...,False,Do Not Notify,?,?,?,?,code 6,Resolved by 9,16/2/2017 16:38,16/2/2017 16:38
141709,INC0121064,Active,True,1,0,1,True,Caller 116,Opened by 12,16/2/2017 14:17,...,False,Do Not Notify,?,?,?,?,code 6,Resolved by 9,16/2/2017 16:38,16/2/2017 16:38
141710,INC0121064,Resolved,True,1,0,2,True,Caller 116,Opened by 12,16/2/2017 14:17,...,True,Do Not Notify,?,?,?,?,code 6,Resolved by 9,16/2/2017 16:38,16/2/2017 16:38
141711,INC0121064,Closed,False,1,0,3,True,Caller 116,Opened by 12,16/2/2017 14:17,...,True,Do Not Notify,?,?,?,?,code 6,Resolved by 9,16/2/2017 16:38,16/2/2017 16:38

In [5]:
df.columns

Index(['number', 'incident_state', 'active', 'reassignment_count',
       'reopen_count', 'sys_mod_count', 'made_sla', 'caller_id', 'opened_by',
       'opened_at', 'sys_created_by', 'sys_created_at', 'sys_updated_by',
       'sys_updated_at', 'contact_type', 'location', 'category', 'subcategory',
       'u_symptom', 'cmdb_ci', 'impact', 'urgency', 'priority',
       'assignment_group', 'assigned_to', 'knowledge',
       'u_priority_confirmation', 'notify', 'problem_id', 'rfc', 'vendor',
       'caused_by', 'closed_code', 'resolved_by', 'resolved_at', 'closed_at'],
      dtype='object')

In [6]:
#droping coulmns that are not rrequired
df = df[['number',
         'opened_at',
         'resolved_at',
         'impact',
         'priority',
         'category',
         'assignment_group',
         'closed_code',
         'incident_state']]
df

,number,opened_at,resolved_at,impact,priority,category,assignment_group,closed_code,incident_state
0,INC0000045,29/2/2016 01:16,29/2/2016 11:29,2 - Medium,3 - Moderate,Category 55,Group 56,code 5,New
1,INC0000045,29/2/2016 01:16,29/2/2016 11:29,2 - Medium,3 - Moderate,Category 55,Group 56,code 5,Resolved
2,INC0000045,29/2/2016 01:16,29/2/2016 11:29,2 - Medium,3 - Moderate,Category 55,Group 56,code 5,Resolved
3,INC0000045,29/2/2016 01:16,29/2/2016 11:29,2 - Medium,3 - Moderate,Category 55,Group 56,code 5,Closed
4,INC0000047,29/2/2016 04:40,1/3/2016 9:52,2 - Medium,3 - Moderate,Category 40,Group 70,code 5,New
...,...,...,...,...,...,...,...,...,...
141707,INC0120835,16/2/2017 09:09,16/2/2017 09:53,2 - Medium,3 - Moderate,Category 42,Group 31,code 9,Closed
141708,INC0121064,16/2/2017 14:17,16/2/2017 16:38,2 - Medium,3 - Moderate,Category 42,Group 70,code 6,Active
141709,INC0121064,16/2/2017 14:17,16/2/2017 16:38,2 - Medium,3 - Moderate,Category 42,Group 31,code 6,Active
141710,INC0121064,16/2/2017 14:17,16/2/2017 16:38,2 - Medium,3 - Moderate,Category 42,Group 31,code 6,Resolved
141711,INC0121064,16/2/2017 14:17,16/2/2017 16:38,2 - Medium,3 - Moderate,Category 42,Group 31,code 6,Closed

In [7]:
#renaming the columns
df = df.rename(columns={
    'number': 'incident_id',
    'opened_at': 'created_at',
    'impact': 'severity',
    'assignment_group': 'team_assigned',
    'close_code': 'root_cause',
    'incident_state': 'status'
})
df

,incident_id,created_at,resolved_at,severity,priority,category,team_assigned,closed_code,status
0,INC0000045,29/2/2016 01:16,29/2/2016 11:29,2 - Medium,3 - Moderate,Category 55,Group 56,code 5,New
1,INC0000045,29/2/2016 01:16,29/2/2016 11:29,2 - Medium,3 - Moderate,Category 55,Group 56,code 5,Resolved
2,INC0000045,29/2/2016 01:16,29/2/2016 11:29,2 - Medium,3 - Moderate,Category 55,Group 56,code 5,Resolved
3,INC0000045,29/2/2016 01:16,29/2/2016 11:29,2 - Medium,3 - Moderate,Category 55,Group 56,code 5,Closed
4,INC0000047,29/2/2016 04:40,1/3/2016 9:52,2 - Medium,3 - Moderate,Category 40,Group 70,code 5,New
...,...,...,...,...,...,...,...,...,...
141707,INC0120835,16/2/2017 09:09,16/2/2017 09:53,2 - Medium,3 - Moderate,Category 42,Group 31,code 9,Closed
141708,INC0121064,16/2/2017 14:17,16/2/2017 16:38,2 - Medium,3 - Moderate,Category 42,Group 70,code 6,Active
141709,INC0121064,16/2/2017 14:17,16/2/2017 16:38,2 - Medium,3 - Moderate,Category 42,Group 31,code 6,Active
141710,INC0121064,16/2/2017 14:17,16/2/2017 16:38,2 - Medium,3 - Moderate,Category 42,Group 31,code 6,Resolved
141711,INC0121064,16/2/2017 14:17,16/2/2017 16:38,2 - Medium,3 - Moderate,Category 42,Group 31,code 6,Closed

In [36]:
# converting event log data by aggregating the columns
incident_df = df.groupby("incident_id").agg({
    "created_at": "min",
    "resolved_at": "max",
    "severity": "first",
    "priority": "first",
    "category": "first",
    "team_assigned": "last",
    "closed_code": "last",
    "status": "last"
}).reset_index()
incident_df

,incident_id,created_at,resolved_at,severity,priority,category,team_assigned,closed_code,status
0,INC0000045,29/2/2016 01:16,29/2/2016 11:29,2 - Medium,3 - Moderate,Category 55,Group 56,code 5,Closed
1,INC0000047,29/2/2016 04:40,1/3/2016 9:52,2 - Medium,3 - Moderate,Category 40,Group 24,code 5,Closed
2,INC0000057,29/2/2016 06:10,1/3/2016 2:55,2 - Medium,3 - Moderate,Category 20,Group 70,code 10,Closed
3,INC0000060,29/2/2016 06:38,2/3/2016 12:06,2 - Medium,3 - Moderate,Category 9,Group 25,code 3,Closed
4,INC0000062,29/2/2016 06:58,29/2/2016 15:51,2 - Medium,3 - Moderate,Category 53,Group 23,code 7,Closed
...,...,...,...,...,...,...,...,...,...
24913,INC0120304,15/2/2017 02:02,17/2/2017 00:47,2 - Medium,3 - Moderate,Category 52,Group 64,code 6,Closed
24914,INC0120319,15/2/2017 07:09,?,3 - Low,4 - Low,Category 50,Group 70,code 6,Closed
24915,INC0120495,15/2/2017 11:58,?,2 - Medium,3 - Moderate,Category 59,Group 24,?,Closed
24916,INC0120835,16/2/2017 09:09,16/2/2017 09:53,2 - Medium,3 - Moderate,Category 42,Group 31,code 9,Closed
24917,INC0121064,16/2/2017 14:17,16/2/2017 16:38,2 - Medium,3 - Moderate,Category 42,Group 31,code 6,Closed

In [37]:
incident_df.isnull().sum()

incident_id      0
created_at       0
resolved_at      0
severity         0
priority         0
category         0
team_assigned    0
closed_code      0
status           0
dtype: int64

In [38]:
#checking for special character values
incident_df.loc[incident_df['resolved_at']=='?']

,incident_id,created_at,resolved_at,severity,priority,category,team_assigned,closed_code,status
26,INC0000093,29/2/2016 08:56,?,2 - Medium,3 - Moderate,Category 61,Group 70,code 7,Closed
71,INC0000160,29/2/2016 10:18,?,2 - Medium,3 - Moderate,Category 53,Group 70,code 7,Closed
90,INC0000199,29/2/2016 11:06,?,3 - Low,4 - Low,Category 42,Group 70,code 11,Closed
116,INC0000269,29/2/2016 13:30,?,2 - Medium,3 - Moderate,Category 26,Group 70,code 9,Closed
127,INC0000290,29/2/2016 13:59,?,2 - Medium,3 - Moderate,Category 45,Group 70,code 10,Closed
...,...,...,...,...,...,...,...,...,...
24910,INC0119987,14/2/2017 11:15,?,3 - Low,4 - Low,Category 50,Group 70,code 6,Closed
24911,INC0120268,14/2/2017 18:31,?,3 - Low,4 - Low,Category 50,Group 70,code 6,Closed
24912,INC0120303,15/2/2017 01:52,?,3 - Low,4 - Low,Category 50,Group 70,code 6,Closed
24914,INC0120319,15/2/2017 07:09,?,3 - Low,4 - Low,Category 50,Group 70,code 6,Closed
24915,INC0120495,15/2/2017 11:58,?,2 - Medium,3 - Moderate,Category 59,Group 24,?,Closed

In [39]:
incident_df['resolved_at'] = incident_df['resolved_at'].replace('?', np.nan)

In [40]:
incident_df.isnull().sum()

incident_id         0
created_at          0
resolved_at      1556
severity            0
priority            0
category            0
team_assigned       0
closed_code         0
status              0
dtype: int64

In [41]:
incident_df['resolved_at'] = pd.to_datetime(incident_df['resolved_at'])
incident_df['created_at'] = pd.to_datetime(incident_df['created_at'])

C:\Users\User\AppData\Local\Temp\ipykernel_5940\3797137903.py:1: UserWarning: Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  incident_df['resolved_at'] = pd.to_datetime(incident_df['resolved_at'])
C:\Users\User\AppData\Local\Temp\ipykernel_5940\3797137903.py:2: UserWarning: Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  incident_df['created_at'] = pd.to_datetime(incident_df['created_at'])

In [42]:
incident_df

,incident_id,created_at,resolved_at,severity,priority,category,team_assigned,closed_code,status
0,INC0000045,2016-02-29 01:16:00,2016-02-29 11:29:00,2 - Medium,3 - Moderate,Category 55,Group 56,code 5,Closed
1,INC0000047,2016-02-29 04:40:00,2016-03-01 09:52:00,2 - Medium,3 - Moderate,Category 40,Group 24,code 5,Closed
2,INC0000057,2016-02-29 06:10:00,2016-03-01 02:55:00,2 - Medium,3 - Moderate,Category 20,Group 70,code 10,Closed
3,INC0000060,2016-02-29 06:38:00,2016-03-02 12:06:00,2 - Medium,3 - Moderate,Category 9,Group 25,code 3,Closed
4,INC0000062,2016-02-29 06:58:00,2016-02-29 15:51:00,2 - Medium,3 - Moderate,Category 53,Group 23,code 7,Closed
...,...,...,...,...,...,...,...,...,...
24913,INC0120304,2017-02-15 02:02:00,2017-02-17 00:47:00,2 - Medium,3 - Moderate,Category 52,Group 64,code 6,Closed
24914,INC0120319,2017-02-15 07:09:00,NaT,3 - Low,4 - Low,Category 50,Group 70,code 6,Closed
24915,INC0120495,2017-02-15 11:58:00,NaT,2 - Medium,3 - Moderate,Category 59,Group 24,?,Closed
24916,INC0120835,2017-02-16 09:09:00,2017-02-16 09:53:00,2 - Medium,3 - Moderate,Category 42,Group 31,code 9,Closed
24917,INC0121064,2017-02-16 14:17:00,2017-02-16 16:38:00,2 - Medium,3 - Moderate,Category 42,Group 31,code 6,Closed

In [45]:
incident_df = incident_df.replace(r'^\s*\?\s*$', 'Unknown', regex=True)
incident_df

,incident_id,created_at,resolved_at,severity,priority,category,team_assigned,closed_code,status
0,INC0000045,2016-02-29 01:16:00,2016-02-29 11:29:00,2 - Medium,3 - Moderate,Category 55,Group 56,code 5,Closed
1,INC0000047,2016-02-29 04:40:00,2016-03-01 09:52:00,2 - Medium,3 - Moderate,Category 40,Group 24,code 5,Closed
2,INC0000057,2016-02-29 06:10:00,2016-03-01 02:55:00,2 - Medium,3 - Moderate,Category 20,Group 70,code 10,Closed
3,INC0000060,2016-02-29 06:38:00,2016-03-02 12:06:00,2 - Medium,3 - Moderate,Category 9,Group 25,code 3,Closed
4,INC0000062,2016-02-29 06:58:00,2016-02-29 15:51:00,2 - Medium,3 - Moderate,Category 53,Group 23,code 7,Closed
...,...,...,...,...,...,...,...,...,...
24913,INC0120304,2017-02-15 02:02:00,2017-02-17 00:47:00,2 - Medium,3 - Moderate,Category 52,Group 64,code 6,Closed
24914,INC0120319,2017-02-15 07:09:00,NaT,3 - Low,4 - Low,Category 50,Group 70,code 6,Closed
24915,INC0120495,2017-02-15 11:58:00,NaT,2 - Medium,3 - Moderate,Category 59,Group 24,Unknown,Closed
24916,INC0120835,2017-02-16 09:09:00,2017-02-16 09:53:00,2 - Medium,3 - Moderate,Category 42,Group 31,code 9,Closed
24917,INC0121064,2017-02-16 14:17:00,2017-02-16 16:38:00,2 - Medium,3 - Moderate,Category 42,Group 31,code 6,Closed

In [46]:
incident_df['status'].unique()

array(['Closed'], dtype=object)

In [49]:
incident_df['is_resolved'] = incident_df['resolved_at'].notna()
incident_df

,incident_id,created_at,resolved_at,severity,priority,category,team_assigned,closed_code,status,is_resolved
0,INC0000045,2016-02-29 01:16:00,2016-02-29 11:29:00,2 - Medium,3 - Moderate,Category 55,Group 56,code 5,Closed,True
1,INC0000047,2016-02-29 04:40:00,2016-03-01 09:52:00,2 - Medium,3 - Moderate,Category 40,Group 24,code 5,Closed,True
2,INC0000057,2016-02-29 06:10:00,2016-03-01 02:55:00,2 - Medium,3 - Moderate,Category 20,Group 70,code 10,Closed,True
3,INC0000060,2016-02-29 06:38:00,2016-03-02 12:06:00,2 - Medium,3 - Moderate,Category 9,Group 25,code 3,Closed,True
4,INC0000062,2016-02-29 06:58:00,2016-02-29 15:51:00,2 - Medium,3 - Moderate,Category 53,Group 23,code 7,Closed,True
...,...,...,...,...,...,...,...,...,...,...
24913,INC0120304,2017-02-15 02:02:00,2017-02-17 00:47:00,2 - Medium,3 - Moderate,Category 52,Group 64,code 6,Closed,True
24914,INC0120319,2017-02-15 07:09:00,NaT,3 - Low,4 - Low,Category 50,Group 70,code 6,Closed,False
24915,INC0120495,2017-02-15 11:58:00,NaT,2 - Medium,3 - Moderate,Category 59,Group 24,Unknown,Closed,False
24916,INC0120835,2017-02-16 09:09:00,2017-02-16 09:53:00,2 - Medium,3 - Moderate,Category 42,Group 31,code 9,Closed,True
24917,INC0121064,2017-02-16 14:17:00,2017-02-16 16:38:00,2 - Medium,3 - Moderate,Category 42,Group 31,code 6,Closed,True

In [50]:
incident_df["resolution_time_hours"] = (
    incident_df["resolved_at"] - incident_df["created_at"]
).dt.total_seconds() / 3600

In [57]:
incident_df

,incident_id,created_at,resolved_at,severity,priority,category,team_assigned,closed_code,status,is_resolved,resolution_time_hours,root_cause
0,INC0000045,2016-02-29 01:16:00,2016-02-29 11:29:00,2 - Medium,3 - Moderate,Category 55,Group 56,code 5,Closed,True,10.216667,Server Overload
1,INC0000047,2016-02-29 04:40:00,2016-03-01 09:52:00,2 - Medium,3 - Moderate,Category 40,Group 24,code 5,Closed,True,29.200000,Server Overload
2,INC0000057,2016-02-29 06:10:00,2016-03-01 02:55:00,2 - Medium,3 - Moderate,Category 20,Group 70,code 10,Closed,True,20.750000,Third-Party Service Failure
3,INC0000060,2016-02-29 06:38:00,2016-03-02 12:06:00,2 - Medium,3 - Moderate,Category 9,Group 25,code 3,Closed,True,53.466667,Application Bug
4,INC0000062,2016-02-29 06:58:00,2016-02-29 15:51:00,2 - Medium,3 - Moderate,Category 53,Group 23,code 7,Closed,True,8.883333,API Timeout
...,...,...,...,...,...,...,...,...,...,...,...,...
24913,INC0120304,2017-02-15 02:02:00,2017-02-17 00:47:00,2 - Medium,3 - Moderate,Category 52,Group 64,code 6,Closed,True,46.750000,Authentication Failure
24914,INC0120319,2017-02-15 07:09:00,NaT,3 - Low,4 - Low,Category 50,Group 70,code 6,Closed,False,NaN,Authentication Failure
24915,INC0120495,2017-02-15 11:58:00,NaT,2 - Medium,3 - Moderate,Category 59,Group 24,Unknown,Closed,False,NaN,Not Documented
24916,INC0120835,2017-02-16 09:09:00,2017-02-16 09:53:00,2 - Medium,3 - Moderate,Category 42,Group 31,code 9,Closed,True,0.733333,Disk Space Issue
24917,INC0121064,2017-02-16 14:17:00,2017-02-16 16:38:00,2 - Medium,3 - Moderate,Category 42,Group 31,code 6,Closed,True,2.350000,Authentication Failure

In [56]:
root_cause_map = {
    "code 1": "Network Failure",
    "code 2": "Database Issue",
    "code 3": "Application Bug",
    "code 4": "Configuration Error",
    "code 5": "Server Overload",
    "code 6": "Authentication Failure",
    "code 7": "API Timeout",
    "code 8": "Memory Leak",
    "code 9": "Disk Space Issue",
    "code 10": "Third-Party Service Failure",
    "code 11": "Data Corruption",
    "code 12": "Security Policy Block",
    "code 13": "Job Scheduling Failure",
    "code 14": "Integration Failure",
    "code 15": "Deployment Error",
    "code 16": "Hardware Failure",
    "code 17": "Unknown System Error",
    "Unknown": "Not Documented"
}

incident_df["root_cause"] = incident_df["closed_code"].map(root_cause_map)

In [58]:
incident_df= incident_df.drop(columns= 'closed_code')

In [59]:
incident_df= incident_df.drop(columns= 'status')
incident_df

,incident_id,created_at,resolved_at,severity,priority,category,team_assigned,is_resolved,resolution_time_hours,root_cause
0,INC0000045,2016-02-29 01:16:00,2016-02-29 11:29:00,2 - Medium,3 - Moderate,Category 55,Group 56,True,10.216667,Server Overload
1,INC0000047,2016-02-29 04:40:00,2016-03-01 09:52:00,2 - Medium,3 - Moderate,Category 40,Group 24,True,29.200000,Server Overload
2,INC0000057,2016-02-29 06:10:00,2016-03-01 02:55:00,2 - Medium,3 - Moderate,Category 20,Group 70,True,20.750000,Third-Party Service Failure
3,INC0000060,2016-02-29 06:38:00,2016-03-02 12:06:00,2 - Medium,3 - Moderate,Category 9,Group 25,True,53.466667,Application Bug
4,INC0000062,2016-02-29 06:58:00,2016-02-29 15:51:00,2 - Medium,3 - Moderate,Category 53,Group 23,True,8.883333,API Timeout
...,...,...,...,...,...,...,...,...,...,...
24913,INC0120304,2017-02-15 02:02:00,2017-02-17 00:47:00,2 - Medium,3 - Moderate,Category 52,Group 64,True,46.750000,Authentication Failure
24914,INC0120319,2017-02-15 07:09:00,NaT,3 - Low,4 - Low,Category 50,Group 70,False,NaN,Authentication Failure
24915,INC0120495,2017-02-15 11:58:00,NaT,2 - Medium,3 - Moderate,Category 59,Group 24,False,NaN,Not Documented
24916,INC0120835,2017-02-16 09:09:00,2017-02-16 09:53:00,2 - Medium,3 - Moderate,Category 42,Group 31,True,0.733333,Disk Space Issue
24917,INC0121064,2017-02-16 14:17:00,2017-02-16 16:38:00,2 - Medium,3 - Moderate,Category 42,Group 31,True,2.350000,Authentication Failure

In [84]:
incident_df['root_cause'].value_counts()

root_cause
Authentication Failure         14882
API Timeout                     4412
Disk Space Issue                2489
Memory Leak                      831
Server Overload                  677
Network Failure                  449
Third-Party Service Failure      314
Data Corruption                  221
Hardware Failure                 171
Configuration Error              130
Not Documented                   107
Application Bug                   99
Database Issue                    59
Deployment Error                  43
Unknown System Error              21
Job Scheduling Failure             8
Integration Failure                3
Security Policy Block              2
Name: count, dtype: int64

In [86]:
incident_df['category'].value_counts().head(10)

category
Category 42    3629
Category 26    3268
Category 53    2655
Category 46    2243
Category 32    1495
Category 9     1141
Category 37    1135
Category 23    1071
Category 20    1067
Category 57     916
Name: count, dtype: int64

In [87]:
incident_df['team_assigned'].value_counts().head(10)

team_assigned
Group 70    9444
Unknown     2157
Group 25    1243
Group 39    1199
Group 24    1060
Group 23     811
Group 64     716
Group 73     576
Group 28     545
Group 27     518
Name: count, dtype: int64

In [88]:
pd.crosstab(incident_df['team_assigned'], incident_df['root_cause'])

root_cause,API Timeout,Application Bug,Authentication Failure,Configuration Error,Data Corruption,Database Issue,Deployment Error,Disk Space Issue,Hardware Failure,Integration Failure,Job Scheduling Failure,Memory Leak,Network Failure,Not Documented,Security Policy Block,Server Overload,Third-Party Service Failure,Unknown System Error
team_assigned,,,,,,,,,,,,,,,,,,
Group 10,14,1,291,0,0,7,0,0,0,0,0,24,4,2,0,0,0,0
Group 12,8,0,41,0,7,0,1,45,0,0,0,9,3,0,0,2,7,0
Group 13,3,0,27,0,0,1,1,0,0,0,0,3,1,0,0,0,0,0
Group 14,0,0,7,1,0,1,0,0,0,0,0,3,1,0,0,0,0,0
Group 15,4,0,38,0,0,0,0,0,0,0,0,12,4,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Group 77,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Group 8,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Group 80,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
Group 9,1,0,93,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
Unknown,673,0,1132,1,3,0,0,224,7,0,0,22,39,3,0,2,51,0

In [90]:
pd.crosstab(incident_df['category'], incident_df['root_cause'])

root_cause,API Timeout,Application Bug,Authentication Failure,Configuration Error,Data Corruption,Database Issue,Deployment Error,Disk Space Issue,Hardware Failure,Integration Failure,Job Scheduling Failure,Memory Leak,Network Failure,Not Documented,Security Policy Block,Server Overload,Third-Party Service Failure,Unknown System Error
category,,,,,,,,,,,,,,,,,,
Category 10,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Category 12,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Category 13,17,1,81,3,1,0,0,5,3,0,0,2,2,0,0,4,0,0
Category 14,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Category 15,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Category 16,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Category 17,9,0,54,0,0,0,0,2,0,0,0,2,2,0,0,2,1,0
Category 19,16,1,151,0,1,0,0,16,7,0,0,7,3,0,0,17,1,0
Category 2,0,0,4,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Category 20,271,5,538,3,11,1,1,148,10,0,0,14,25,1,0,31,8,0
Category 21,0,0,6,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0
Category 22,4,1,20,0,0,0,0,1,18,0,0,1,0,0,0,0,2,0
Category 23,138,7,623,5,21,3,0,146,26,0,0,31,19,0,0,36,15,1
Category 24,23,1,503,4,6,1,0,27,3,0,0,8,6,1,0,49,4,2
Category 25,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
Category 26,849,6,1647,31,37,3,0,467,8,0,1,30,54,0,0,62,65,8
Category 27,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Category 28,33,4,401,2,2,1,0,26,15,0,0,18,5,1,0,13,1,0
Category 29,0,0,5,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
Category 3,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Category 30,1,0,3,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
Category 31,2,0,14,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0
Category 32,417,2,790,3,5,1,1,198,3,0,0,16,14,0,0,19,26,0
Category 33,0,0,14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Category 34,19,1,393,1,6,1,0,14,4,1,0,12,4,0,0,36,6,0
Category 35,169,1,244,1,0,0,0,84,0,0,0,2,1,0,0,4,5,1
Category 36,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
Category 37,138,2,728,1,13,0,0,124,10,1,0,54,10,5,0,23,26,0
Category 38,7,1,10,0,1,0,1,7,0,0,0,8,0,0,0,2,0,0
Category 4,0,0,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Category 40,106,2,393,6,26,1,0,52,5,0,0,26,27,4,0,30,8,0
Category 41,1,0,8,0,0,0,27,0,0,0,0,0,0,0,0,0,0,0
Category 42,893,5,2145,6,9,4,4,404,5,0,1,70,38,6,1,17,21,0
Category 43,25,1,116,2,0,1,1,12,0,0,0,8,4,0,0,0,2,0
Category 44,49,2,238,4,1,0,0,9,0,0,0,17,4,0,0,1,6,0
Category 45,73,4,396,4,3,12,0,24,3,0,0,56,28,8,0,6,8,0
Category 46,330,4,1363,15,5,11,1,74,1,0,0,315,89,4,0,11,20,0
Category 47,0,0,3,0,0,0,0,1,0,0,0,2,0,0,0,0,0,0
Category 48,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Category 49,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Category 5,0,0,9,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
Category 50,4,0,17,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0
Category 51,20,3,489,2,1,0,0,13,0,0,0,7,2,0,0,6,2,0
Category 52,0,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Category 53,446,25,1423,12,25,5,2,425,8,0,3,63,48,10,0,110,43,7
Category 54,4,0,20,0,0,0,0,4,0,0,0,1,0,0,0,0,0,0
Category 55,21,0,41,2,1,0,0,7,0,0,0,1,13,2,0,8,2,1
Category 56,5,0,23,0,0,2,0,1,0,0,1,1,0,1,0,0,1,0
Category 57,140,5,546,1,8,5,2,69,1,0,1,20,19,60,0,25,14,0
Category 59,1,0,4,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
Category 6,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Category 61,75,2,583,15,13,2,1,39,26,1,1,9,7,0,0,28,3,0
Category 62,3,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0
Category 63,1,0,8,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0
Category 7,2,0,23,0,1,0,0,3,0,0,0,1,0,0,0,1,0,0
Category 8,4,1,42,0,1,0,1,2,0,0,0,1,0,0,0,0,0,0
Category 9,87,10,721,6,22,3,1,76,13,0,0,25,19,0,0,134,23,1
Unknown,8,2,14,0,1,1,0,5,1,0,0,1,4,2,0,0,0,0

In [91]:
#creating shift column
incident_df['shift'] = incident_df['created_at'].dt.hour.apply(
    lambda x: 'Night' if x < 7 else ('Morning' if x < 15 else 'Evening')
)

In [92]:
incident_df

,incident_id,created_at,resolved_at,severity,priority,category,team_assigned,is_resolved,resolution_time_hours,root_cause,shift
0,INC0000045,2016-02-29 01:16:00,2016-02-29 11:29:00,2 - Medium,3 - Moderate,Category 55,Group 56,True,10.216667,Server Overload,Night
1,INC0000047,2016-02-29 04:40:00,2016-03-01 09:52:00,2 - Medium,3 - Moderate,Category 40,Group 24,True,29.200000,Server Overload,Night
2,INC0000057,2016-02-29 06:10:00,2016-03-01 02:55:00,2 - Medium,3 - Moderate,Category 20,Group 70,True,20.750000,Third-Party Service Failure,Night
3,INC0000060,2016-02-29 06:38:00,2016-03-02 12:06:00,2 - Medium,3 - Moderate,Category 9,Group 25,True,53.466667,Application Bug,Night
4,INC0000062,2016-02-29 06:58:00,2016-02-29 15:51:00,2 - Medium,3 - Moderate,Category 53,Group 23,True,8.883333,API Timeout,Night
...,...,...,...,...,...,...,...,...,...,...,...
24913,INC0120304,2017-02-15 02:02:00,2017-02-17 00:47:00,2 - Medium,3 - Moderate,Category 52,Group 64,True,46.750000,Authentication Failure,Night
24914,INC0120319,2017-02-15 07:09:00,NaT,3 - Low,4 - Low,Category 50,Group 70,False,NaN,Authentication Failure,Morning
24915,INC0120495,2017-02-15 11:58:00,NaT,2 - Medium,3 - Moderate,Category 59,Group 24,False,NaN,Not Documented,Morning
24916,INC0120835,2017-02-16 09:09:00,2017-02-16 09:53:00,2 - Medium,3 - Moderate,Category 42,Group 31,True,0.733333,Disk Space Issue,Morning
24917,INC0121064,2017-02-16 14:17:00,2017-02-16 16:38:00,2 - Medium,3 - Moderate,Category 42,Group 31,True,2.350000,Authentication Failure,Morning

In [93]:
incident_df["hour"] = incident_df["created_at"].dt.hour
incident_df["day_of_week"] = incident_df["created_at"].dt.day_name()
incident_df["month"] = incident_df["created_at"].dt.month_name()

In [94]:
incident_df

,incident_id,created_at,resolved_at,severity,priority,category,team_assigned,is_resolved,resolution_time_hours,root_cause,shift,hour,day_of_week,month
0,INC0000045,2016-02-29 01:16:00,2016-02-29 11:29:00,2 - Medium,3 - Moderate,Category 55,Group 56,True,10.216667,Server Overload,Night,1,Monday,February
1,INC0000047,2016-02-29 04:40:00,2016-03-01 09:52:00,2 - Medium,3 - Moderate,Category 40,Group 24,True,29.200000,Server Overload,Night,4,Monday,February
2,INC0000057,2016-02-29 06:10:00,2016-03-01 02:55:00,2 - Medium,3 - Moderate,Category 20,Group 70,True,20.750000,Third-Party Service Failure,Night,6,Monday,February
3,INC0000060,2016-02-29 06:38:00,2016-03-02 12:06:00,2 - Medium,3 - Moderate,Category 9,Group 25,True,53.466667,Application Bug,Night,6,Monday,February
4,INC0000062,2016-02-29 06:58:00,2016-02-29 15:51:00,2 - Medium,3 - Moderate,Category 53,Group 23,True,8.883333,API Timeout,Night,6,Monday,February
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24913,INC0120304,2017-02-15 02:02:00,2017-02-17 00:47:00,2 - Medium,3 - Moderate,Category 52,Group 64,True,46.750000,Authentication Failure,Night,2,Wednesday,February
24914,INC0120319,2017-02-15 07:09:00,NaT,3 - Low,4 - Low,Category 50,Group 70,False,NaN,Authentication Failure,Morning,7,Wednesday,February
24915,INC0120495,2017-02-15 11:58:00,NaT,2 - Medium,3 - Moderate,Category 59,Group 24,False,NaN,Not Documented,Morning,11,Wednesday,February
24916,INC0120835,2017-02-16 09:09:00,2017-02-16 09:53:00,2 - Medium,3 - Moderate,Category 42,Group 31,True,0.733333,Disk Space Issue,Morning,9,Thursday,February
24917,INC0121064,2017-02-16 14:17:00,2017-02-16 16:38:00,2 - Medium,3 - Moderate,Category 42,Group 31,True,2.350000,Authentication Failure,Morning,14,Thursday,February

In [96]:
incident_df['resolution_time_hours'].describe()

count    23362.000000
mean       178.171582
std        532.787772
min          0.000000
25%          0.416667
50%         22.100000
75%        148.479167
max       8070.166667
Name: resolution_time_hours, dtype: float64

In [100]:
def sla_map(x, y):
    if x == '1 - Critical' and y > 24:
        return 'Yes'
    elif x == '2 - High' and y > 84:
        return 'Yes'
    elif x == '3 - Morderate' and y > 168:
        return 'Yes'
    else:
        return 'No'
    

incident_df['sla_breach'] = incident_df.apply(
    lambda row: sla_map(row['priority'], row['resolution_time_hours']),
    axis=1
)

In [108]:
incident_df.loc[incident_df['sla_breach'] == 'Yes']

,incident_id,created_at,resolved_at,severity,priority,category,team_assigned,is_resolved,resolution_time_hours,root_cause,shift,hour,day_of_week,month,sla_breach
200,INC0000433,2016-02-29 20:32:00,2016-03-25 23:57:00,1 - High,1 - Critical,Category 19,Group 61,True,603.416667,API Timeout,Evening,20,Monday,February,Yes
224,INC0000508,2016-03-01 08:18:00,2016-03-17 18:51:00,1 - High,2 - High,Category 51,Group 25,True,394.550000,Authentication Failure,Morning,8,Tuesday,March,Yes
231,INC0000517,2016-03-01 08:35:00,2016-04-19 11:09:00,1 - High,1 - Critical,Category 45,Group 72,True,1178.566667,Data Corruption,Morning,8,Tuesday,March,Yes
254,INC0000548,2016-03-01 09:19:00,2016-03-04 11:02:00,1 - High,1 - Critical,Category 42,Group 31,True,73.716667,API Timeout,Morning,9,Tuesday,March,Yes
283,INC0000594,2016-03-01 10:16:00,2016-03-17 11:11:00,2 - Medium,2 - High,Category 55,Group 65,True,384.916667,Authentication Failure,Morning,10,Tuesday,March,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24563,INC0034334,2016-05-31 14:58:00,2016-06-06 12:29:00,1 - High,2 - High,Category 61,Group 73,True,141.516667,Authentication Failure,Morning,14,Tuesday,May,Yes
24733,INC0092643,2016-12-02 23:59:00,2016-12-05 11:47:00,1 - High,1 - Critical,Category 45,Group 15,True,59.800000,Network Failure,Evening,23,Friday,December,Yes
24806,INC0106327,2017-01-10 16:03:00,2017-01-12 08:28:00,1 - High,1 - Critical,Category 29,Group 14,True,40.416667,Authentication Failure,Evening,16,Tuesday,January,Yes
24831,INC0109599,2017-01-18 08:42:00,2017-02-07 09:57:00,1 - High,2 - High,Category 59,Group 74,True,481.250000,API Timeout,Morning,8,Wednesday,January,Yes
24862,INC0114952,2017-01-31 22:36:00,2017-02-09 14:24:00,2 - Medium,2 - High,Category 42,Group 3,True,207.800000,API Timeout,Evening,22,Tuesday,January,Yes