In [17]:
import pandas as pd

In [4]:
df = pd.read_csv('C:\\Users\\User\\Downloads\\incident+management+process+enriched+event+log\\incident_event_log.csv')
df

,number,incident_state,active,reassignment_count,reopen_count,sys_mod_count,made_sla,caller_id,opened_by,opened_at,...,u_priority_confirmation,notify,problem_id,rfc,vendor,caused_by,closed_code,resolved_by,resolved_at,closed_at
0,INC0000045,New,True,0,0,0,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
1,INC0000045,Resolved,True,0,0,2,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
2,INC0000045,Resolved,True,0,0,3,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
3,INC0000045,Closed,False,0,0,4,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
4,INC0000047,New,True,0,0,0,True,Caller 2403,Opened by 397,29/2/2016 04:40,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 81,1/3/2016 09:52,6/3/2016 10:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141707,INC0120835,Closed,False,1,0,4,True,Caller 116,Opened by 12,16/2/2017 09:09,...,True,Do Not Notify,?,?,?,?,code 9,Resolved by 9,16/2/2017 09:53,16/2/2017 09:53
141708,INC0121064,Active,True,0,0,0,True,Caller 116,Opened by 12,16/2/2017 14:17,...,False,Do Not Notify,?,?,?,?,code 6,Resolved by 9,16/2/2017 16:38,16/2/2017 16:38
141709,INC0121064,Active,True,1,0,1,True,Caller 116,Opened by 12,16/2/2017 14:17,...,False,Do Not Notify,?,?,?,?,code 6,Resolved by 9,16/2/2017 16:38,16/2/2017 16:38
141710,INC0121064,Resolved,True,1,0,2,True,Caller 116,Opened by 12,16/2/2017 14:17,...,True,Do Not Notify,?,?,?,?,code 6,Resolved by 9,16/2/2017 16:38,16/2/2017 16:38
141711,INC0121064,Closed,False,1,0,3,True,Caller 116,Opened by 12,16/2/2017 14:17,...,True,Do Not Notify,?,?,?,?,code 6,Resolved by 9,16/2/2017 16:38,16/2/2017 16:38

In [ ]:
#droping coulmns that are not rrequired
df = df[['number',
         'opened_at',
         'resolved_at',
         'impact',
         'category',
         'assignment_group',
         'closed_code',
         'incident_state']]
df

In [16]:
#renaming the columns
df = df.rename(columns={
    'number': 'incident_id',
    'opened_at': 'created_at',
    'impact': 'severity',
    'assignment_group': 'team_assigned',
    'close_code': 'root_cause',
    'incident_state': 'status'
})
df

,incident_id,created_at,resolved_at,severity,category,team_assigned,closed_code,status
0,INC0000045,29/2/2016 01:16,29/2/2016 11:29,2 - Medium,Category 55,Group 56,code 5,New
1,INC0000045,29/2/2016 01:16,29/2/2016 11:29,2 - Medium,Category 55,Group 56,code 5,Resolved
2,INC0000045,29/2/2016 01:16,29/2/2016 11:29,2 - Medium,Category 55,Group 56,code 5,Resolved
3,INC0000045,29/2/2016 01:16,29/2/2016 11:29,2 - Medium,Category 55,Group 56,code 5,Closed
4,INC0000047,29/2/2016 04:40,1/3/2016 09:52,2 - Medium,Category 40,Group 70,code 5,New
...,...,...,...,...,...,...,...,...
141707,INC0120835,16/2/2017 09:09,16/2/2017 09:53,2 - Medium,Category 42,Group 31,code 9,Closed
141708,INC0121064,16/2/2017 14:17,16/2/2017 16:38,2 - Medium,Category 42,Group 70,code 6,Active
141709,INC0121064,16/2/2017 14:17,16/2/2017 16:38,2 - Medium,Category 42,Group 31,code 6,Active
141710,INC0121064,16/2/2017 14:17,16/2/2017 16:38,2 - Medium,Category 42,Group 31,code 6,Resolved
141711,INC0121064,16/2/2017 14:17,16/2/2017 16:38,2 - Medium,Category 42,Group 31,code 6,Closed

In [18]:
df['created_at'] = pd.to_datetime(df['created_at'])

C:\Users\User\AppData\Local\Temp\ipykernel_28492\3785412646.py:1: UserWarning: Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['created_at'] = pd.to_datetime(df['created_at'])

In [20]:
df['shift'] = df['created_at'].dt.hour.apply(
    lambda x: 'Night' if x < 8 else ('Morning' if x < 16 else 'Evening')
)

In [21]:
df

,incident_id,created_at,resolved_at,severity,category,team_assigned,closed_code,status,shift
0,INC0000045,2016-02-29 01:16:00,29/2/2016 11:29,2 - Medium,Category 55,Group 56,code 5,New,Night
1,INC0000045,2016-02-29 01:16:00,29/2/2016 11:29,2 - Medium,Category 55,Group 56,code 5,Resolved,Night
2,INC0000045,2016-02-29 01:16:00,29/2/2016 11:29,2 - Medium,Category 55,Group 56,code 5,Resolved,Night
3,INC0000045,2016-02-29 01:16:00,29/2/2016 11:29,2 - Medium,Category 55,Group 56,code 5,Closed,Night
4,INC0000047,2016-02-29 04:40:00,1/3/2016 09:52,2 - Medium,Category 40,Group 70,code 5,New,Night
...,...,...,...,...,...,...,...,...,...
141707,INC0120835,2017-02-16 09:09:00,16/2/2017 09:53,2 - Medium,Category 42,Group 31,code 9,Closed,Morning
141708,INC0121064,2017-02-16 14:17:00,16/2/2017 16:38,2 - Medium,Category 42,Group 70,code 6,Active,Morning
141709,INC0121064,2017-02-16 14:17:00,16/2/2017 16:38,2 - Medium,Category 42,Group 31,code 6,Active,Morning
141710,INC0121064,2017-02-16 14:17:00,16/2/2017 16:38,2 - Medium,Category 42,Group 31,code 6,Resolved,Morning
141711,INC0121064,2017-02-16 14:17:00,16/2/2017 16:38,2 - Medium,Category 42,Group 31,code 6,Closed,Morning

In [56]:
incident_df = df.groupby("incident_id").agg({
    "created_at": "min",
    "resolved_at": "max",
    "severity": "first",
    "category": "first",
    "team_assigned": "last",
    "closed_code": "last",
    "status": "last"
}).reset_index()
incident_df

,incident_id,created_at,resolved_at,severity,category,team_assigned,closed_code,status
0,INC0000045,2016-02-29 01:16:00,29/2/2016 11:29,2 - Medium,Category 55,Group 56,code 5,Closed
1,INC0000047,2016-02-29 04:40:00,1/3/2016 09:52,2 - Medium,Category 40,Group 24,code 5,Closed
2,INC0000057,2016-02-29 06:10:00,1/3/2016 02:55,2 - Medium,Category 20,Group 70,code 10,Closed
3,INC0000060,2016-02-29 06:38:00,2/3/2016 12:06,2 - Medium,Category 9,Group 25,code 3,Closed
4,INC0000062,2016-02-29 06:58:00,29/2/2016 15:51,2 - Medium,Category 53,Group 23,code 7,Closed
...,...,...,...,...,...,...,...,...
24913,INC0120304,2017-02-15 02:02:00,17/2/2017 00:47,2 - Medium,Category 52,Group 64,code 6,Closed
24914,INC0120319,2017-02-15 07:09:00,?,3 - Low,Category 50,Group 70,code 6,Closed
24915,INC0120495,2017-02-15 11:58:00,?,2 - Medium,Category 59,Group 24,?,Closed
24916,INC0120835,2017-02-16 09:09:00,16/2/2017 09:53,2 - Medium,Category 42,Group 31,code 9,Closed
24917,INC0121064,2017-02-16 14:17:00,16/2/2017 16:38,2 - Medium,Category 42,Group 31,code 6,Closed

In [49]:
incident_df.isnull().sum()

incident_id      0
created_at       0
resolved_at      0
severity         0
category         0
team_assigned    0
closed_code      0
status           0
dtype: int64

In [61]:
unres= incident_df[incident_df['resolved_at']=='?']

In [62]:
unres

,incident_id,created_at,resolved_at,severity,category,team_assigned,closed_code,status
26,INC0000093,2016-02-29 08:56:00,?,2 - Medium,Category 61,Group 70,code 7,Closed
71,INC0000160,2016-02-29 10:18:00,?,2 - Medium,Category 53,Group 70,code 7,Closed
90,INC0000199,2016-02-29 11:06:00,?,3 - Low,Category 42,Group 70,code 11,Closed
116,INC0000269,2016-02-29 13:30:00,?,2 - Medium,Category 26,Group 70,code 9,Closed
127,INC0000290,2016-02-29 13:59:00,?,2 - Medium,Category 45,Group 70,code 10,Closed
...,...,...,...,...,...,...,...,...
24910,INC0119987,2017-02-14 11:15:00,?,3 - Low,Category 50,Group 70,code 6,Closed
24911,INC0120268,2017-02-14 18:31:00,?,3 - Low,Category 50,Group 70,code 6,Closed
24912,INC0120303,2017-02-15 01:52:00,?,3 - Low,Category 50,Group 70,code 6,Closed
24914,INC0120319,2017-02-15 07:09:00,?,3 - Low,Category 50,Group 70,code 6,Closed
24915,INC0120495,2017-02-15 11:58:00,?,2 - Medium,Category 59,Group 24,?,Closed

In [104]:
res_inc_df= incident_df[incident_df['resolved_at']!='?']

In [105]:
res_inc_df

,incident_id,created_at,resolved_at,severity,category,team_assigned,closed_code,status
0,INC0000045,2016-02-29 01:16:00,29/2/2016 11:29,2 - Medium,Category 55,Group 56,code 5,Closed
1,INC0000047,2016-02-29 04:40:00,1/3/2016 09:52,2 - Medium,Category 40,Group 24,code 5,Closed
2,INC0000057,2016-02-29 06:10:00,1/3/2016 02:55,2 - Medium,Category 20,Group 70,code 10,Closed
3,INC0000060,2016-02-29 06:38:00,2/3/2016 12:06,2 - Medium,Category 9,Group 25,code 3,Closed
4,INC0000062,2016-02-29 06:58:00,29/2/2016 15:51,2 - Medium,Category 53,Group 23,code 7,Closed
...,...,...,...,...,...,...,...,...
24903,INC0118999,2017-02-10 15:55:00,10/2/2017 16:35,2 - Medium,Category 4,Group 53,code 6,Closed
24906,INC0119390,2017-02-13 10:33:00,14/2/2017 09:37,2 - Medium,?,Group 39,code 6,Closed
24913,INC0120304,2017-02-15 02:02:00,17/2/2017 00:47,2 - Medium,Category 52,Group 64,code 6,Closed
24916,INC0120835,2017-02-16 09:09:00,16/2/2017 09:53,2 - Medium,Category 42,Group 31,code 9,Closed
24917,INC0121064,2017-02-16 14:17:00,16/2/2017 16:38,2 - Medium,Category 42,Group 31,code 6,Closed

In [106]:
res_inc_df['resolved_at'] = pd.to_datetime(res_inc_df['resolved_at'])
res_inc_df

C:\Users\User\AppData\Local\Temp\ipykernel_28492\1991305317.py:1: UserWarning: Parsing dates in %d/%m/%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  res_inc_df['resolved_at'] = pd.to_datetime(res_inc_df['resolved_at'])
C:\Users\User\AppData\Local\Temp\ipykernel_28492\1991305317.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  res_inc_df['resolved_at'] = pd.to_datetime(res_inc_df['resolved_at'])

,incident_id,created_at,resolved_at,severity,category,team_assigned,closed_code,status
0,INC0000045,2016-02-29 01:16:00,2016-02-29 11:29:00,2 - Medium,Category 55,Group 56,code 5,Closed
1,INC0000047,2016-02-29 04:40:00,2016-03-01 09:52:00,2 - Medium,Category 40,Group 24,code 5,Closed
2,INC0000057,2016-02-29 06:10:00,2016-03-01 02:55:00,2 - Medium,Category 20,Group 70,code 10,Closed
3,INC0000060,2016-02-29 06:38:00,2016-03-02 12:06:00,2 - Medium,Category 9,Group 25,code 3,Closed
4,INC0000062,2016-02-29 06:58:00,2016-02-29 15:51:00,2 - Medium,Category 53,Group 23,code 7,Closed
...,...,...,...,...,...,...,...,...
24903,INC0118999,2017-02-10 15:55:00,2017-02-10 16:35:00,2 - Medium,Category 4,Group 53,code 6,Closed
24906,INC0119390,2017-02-13 10:33:00,2017-02-14 09:37:00,2 - Medium,?,Group 39,code 6,Closed
24913,INC0120304,2017-02-15 02:02:00,2017-02-17 00:47:00,2 - Medium,Category 52,Group 64,code 6,Closed
24916,INC0120835,2017-02-16 09:09:00,2017-02-16 09:53:00,2 - Medium,Category 42,Group 31,code 9,Closed
24917,INC0121064,2017-02-16 14:17:00,2017-02-16 16:38:00,2 - Medium,Category 42,Group 31,code 6,Closed

In [119]:
res_inc_df["resolution_time_hours"] = (
    res_inc_df["resolved_at"] - res_inc_df["created_at"]
).dt.total_seconds() / 3600

In [107]:
res_inc_df

,incident_id,created_at,resolved_at,severity,category,team_assigned,closed_code,status
0,INC0000045,2016-02-29 01:16:00,2016-02-29 11:29:00,2 - Medium,Category 55,Group 56,code 5,Closed
1,INC0000047,2016-02-29 04:40:00,2016-03-01 09:52:00,2 - Medium,Category 40,Group 24,code 5,Closed
2,INC0000057,2016-02-29 06:10:00,2016-03-01 02:55:00,2 - Medium,Category 20,Group 70,code 10,Closed
3,INC0000060,2016-02-29 06:38:00,2016-03-02 12:06:00,2 - Medium,Category 9,Group 25,code 3,Closed
4,INC0000062,2016-02-29 06:58:00,2016-02-29 15:51:00,2 - Medium,Category 53,Group 23,code 7,Closed
...,...,...,...,...,...,...,...,...
24903,INC0118999,2017-02-10 15:55:00,2017-02-10 16:35:00,2 - Medium,Category 4,Group 53,code 6,Closed
24906,INC0119390,2017-02-13 10:33:00,2017-02-14 09:37:00,2 - Medium,?,Group 39,code 6,Closed
24913,INC0120304,2017-02-15 02:02:00,2017-02-17 00:47:00,2 - Medium,Category 52,Group 64,code 6,Closed
24916,INC0120835,2017-02-16 09:09:00,2017-02-16 09:53:00,2 - Medium,Category 42,Group 31,code 9,Closed
24917,INC0121064,2017-02-16 14:17:00,2017-02-16 16:38:00,2 - Medium,Category 42,Group 31,code 6,Closed

In [108]:
res_inc_df=res_inc_df.reset_index()

In [109]:
res_inc_df=res_inc_df.drop(columns= 'index')

In [110]:
res_inc_df

,incident_id,created_at,resolved_at,severity,category,team_assigned,closed_code,status
0,INC0000045,2016-02-29 01:16:00,2016-02-29 11:29:00,2 - Medium,Category 55,Group 56,code 5,Closed
1,INC0000047,2016-02-29 04:40:00,2016-03-01 09:52:00,2 - Medium,Category 40,Group 24,code 5,Closed
2,INC0000057,2016-02-29 06:10:00,2016-03-01 02:55:00,2 - Medium,Category 20,Group 70,code 10,Closed
3,INC0000060,2016-02-29 06:38:00,2016-03-02 12:06:00,2 - Medium,Category 9,Group 25,code 3,Closed
4,INC0000062,2016-02-29 06:58:00,2016-02-29 15:51:00,2 - Medium,Category 53,Group 23,code 7,Closed
...,...,...,...,...,...,...,...,...
23357,INC0118999,2017-02-10 15:55:00,2017-02-10 16:35:00,2 - Medium,Category 4,Group 53,code 6,Closed
23358,INC0119390,2017-02-13 10:33:00,2017-02-14 09:37:00,2 - Medium,?,Group 39,code 6,Closed
23359,INC0120304,2017-02-15 02:02:00,2017-02-17 00:47:00,2 - Medium,Category 52,Group 64,code 6,Closed
23360,INC0120835,2017-02-16 09:09:00,2017-02-16 09:53:00,2 - Medium,Category 42,Group 31,code 9,Closed
23361,INC0121064,2017-02-16 14:17:00,2017-02-16 16:38:00,2 - Medium,Category 42,Group 31,code 6,Closed

In [111]:
res_inc_df['closed_code']=res_inc_df['closed_code'].replace('?','Unknown')

In [132]:
res_inc_df.loc[res_inc_df['closed_code']=='Unknown']

,incident_id,created_at,resolved_at,severity,category,team_assigned,closed_code,status,resolution_time_hours
223,INC0000519,2016-03-01 08:37:00,2016-03-02 11:07:00,2 - Medium,Category 20,Group 28,Unknown,Closed,26.500000
428,INC0000828,2016-03-01 16:04:00,2016-03-02 09:47:00,1 - High,Unknown,Unknown,Unknown,Closed,17.716667
438,INC0000839,2016-03-01 16:35:00,2016-03-02 10:53:00,2 - Medium,Category 24,Group 28,Unknown,Closed,18.300000
511,INC0000959,2016-03-02 04:02:00,2016-03-03 09:52:00,2 - Medium,Category 37,Group 65,Unknown,Closed,29.833333
630,INC0001117,2016-03-02 10:31:00,2016-04-27 10:16:00,2 - Medium,Category 53,Group 68,Unknown,Closed,1343.750000
...,...,...,...,...,...,...,...,...,...
22511,INC0033587,2016-05-30 08:53:00,2016-05-30 10:57:00,2 - Medium,Category 57,Group 65,Unknown,Closed,2.066667
22689,INC0033828,2016-05-30 13:18:00,2016-06-03 09:25:00,2 - Medium,Category 37,Group 65,Unknown,Closed,92.116667
22730,INC0033877,2016-05-30 15:01:00,2016-06-03 11:01:00,2 - Medium,Category 57,Group 65,Unknown,Closed,92.000000
22823,INC0034018,2016-05-31 06:26:00,2016-05-31 09:29:00,2 - Medium,Category 57,Group 65,Unknown,Closed,3.050000
23108,INC0046429,2016-07-12 08:08:00,2016-07-12 09:11:00,2 - Medium,Category 56,Group 65,Unknown,Closed,1.050000

In [124]:
res_inc_df['team_assigned']= res_inc_df['team_assigned'].replace('?','Unknown')

In [115]:
res_inc_df['category']=res_inc_df['category'].replace('?','Unknown')

In [129]:
res_inc_df 
#cleaned data with no missing values and confusing values replaced and removed.

,incident_id,created_at,resolved_at,severity,category,team_assigned,closed_code,status,resolution_time_hours
0,INC0000045,2016-02-29 01:16:00,2016-02-29 11:29:00,2 - Medium,Category 55,Group 56,code 5,Closed,10.216667
1,INC0000047,2016-02-29 04:40:00,2016-03-01 09:52:00,2 - Medium,Category 40,Group 24,code 5,Closed,29.200000
2,INC0000057,2016-02-29 06:10:00,2016-03-01 02:55:00,2 - Medium,Category 20,Group 70,code 10,Closed,20.750000
3,INC0000060,2016-02-29 06:38:00,2016-03-02 12:06:00,2 - Medium,Category 9,Group 25,code 3,Closed,53.466667
4,INC0000062,2016-02-29 06:58:00,2016-02-29 15:51:00,2 - Medium,Category 53,Group 23,code 7,Closed,8.883333
...,...,...,...,...,...,...,...,...,...
23357,INC0118999,2017-02-10 15:55:00,2017-02-10 16:35:00,2 - Medium,Category 4,Group 53,code 6,Closed,0.666667
23358,INC0119390,2017-02-13 10:33:00,2017-02-14 09:37:00,2 - Medium,Unknown,Group 39,code 6,Closed,23.066667
23359,INC0120304,2017-02-15 02:02:00,2017-02-17 00:47:00,2 - Medium,Category 52,Group 64,code 6,Closed,46.750000
23360,INC0120835,2017-02-16 09:09:00,2017-02-16 09:53:00,2 - Medium,Category 42,Group 31,code 9,Closed,0.733333
23361,INC0121064,2017-02-16 14:17:00,2017-02-16 16:38:00,2 - Medium,Category 42,Group 31,code 6,Closed,2.350000

In [159]:
res_inc_df['team_assigned'].unique()

array(['Group 56', 'Group 24', 'Group 70', 'Group 25', 'Group 23',
       'Group 28', 'Group 33', 'Group 54', 'Group 29', 'Group 66',
       'Group 65', 'Group 72', 'Group 30', 'Group 55', 'Group 47',
       'Group 22', 'Group 27', 'Group 39', 'Group 73', 'Group 20',
       'Group 46', 'Group 74', 'Group 5', 'Group 12', 'Group 69',
       'Group 3', 'Group 31', 'Group 26', 'Unknown', 'Group 76',
       'Group 6', 'Group 61', 'Group 15', 'Group 48', 'Group 37',
       'Group 60', 'Group 14', 'Group 10', 'Group 68', 'Group 49',
       'Group 59', 'Group 67', 'Group 64', 'Group 53', 'Group 57',
       'Group 75', 'Group 19', 'Group 58', 'Group 21', 'Group 13',
       'Group 51', 'Group 45', 'Group 50', 'Group 34', 'Group 17',
       'Group 35', 'Group 62', 'Group 9', 'Group 32', 'Group 36',
       'Group 63', 'Group 44', 'Group 2', 'Group 43', 'Group 71',
       'Group 80', 'Group 18', 'Group 41', 'Group 77', 'Group 7',
       'Group 8'], dtype=object)

In [145]:
root_cause_map = {
    "code 1": "Network Failure",
    "code 2": "Database Issue",
    "code 3": "Application Bug",
    "code 4": "Configuration Error",
    "code 5": "Server Overload",
    "code 6": "Authentication Failure",
    "code 7": "API Timeout",
    "code 8": "Memory Leak",
    "code 9": "Disk Space Issue",
    "code 10": "Third-Party Service Failure",
    "code 11": "Data Corruption",
    "code 12": "Security Policy Block",
    "code 13": "Job Scheduling Failure",
    "code 14": "Integration Failure",
    "code 15": "Deployment Error",
    "code 16": "Hardware Failure",
    "code 17": "Unknown System Error",
    "Unknown": "Not Documented"
}

res_inc_df["root_cause"] = res_inc_df["closed_code"].map(root_cause_map)

In [148]:
res_inc_df= res_inc_df.drop(columns= 'closed_code')

In [150]:
res_inc_df= res_inc_df.drop(columns= 'status')
res_inc_df

,incident_id,created_at,resolved_at,severity,category,team_assigned,resolution_time_hours,root_cause
0,INC0000045,2016-02-29 01:16:00,2016-02-29 11:29:00,2 - Medium,Category 55,Group 56,10.216667,Server Overload
1,INC0000047,2016-02-29 04:40:00,2016-03-01 09:52:00,2 - Medium,Category 40,Group 24,29.200000,Server Overload
2,INC0000057,2016-02-29 06:10:00,2016-03-01 02:55:00,2 - Medium,Category 20,Group 70,20.750000,Third-Party Service Failure
3,INC0000060,2016-02-29 06:38:00,2016-03-02 12:06:00,2 - Medium,Category 9,Group 25,53.466667,Application Bug
4,INC0000062,2016-02-29 06:58:00,2016-02-29 15:51:00,2 - Medium,Category 53,Group 23,8.883333,API Timeout
...,...,...,...,...,...,...,...,...
23357,INC0118999,2017-02-10 15:55:00,2017-02-10 16:35:00,2 - Medium,Category 4,Group 53,0.666667,Authentication Failure
23358,INC0119390,2017-02-13 10:33:00,2017-02-14 09:37:00,2 - Medium,Unknown,Group 39,23.066667,Authentication Failure
23359,INC0120304,2017-02-15 02:02:00,2017-02-17 00:47:00,2 - Medium,Category 52,Group 64,46.750000,Authentication Failure
23360,INC0120835,2017-02-16 09:09:00,2017-02-16 09:53:00,2 - Medium,Category 42,Group 31,0.733333,Disk Space Issue
23361,INC0121064,2017-02-16 14:17:00,2017-02-16 16:38:00,2 - Medium,Category 42,Group 31,2.350000,Authentication Failure

In [154]:
# extracting numbers from category, to convert them into meaningful values.

res_inc_df["category_num"] = res_inc_df["category"].str.extract(r'(\d+)')
res_inc_df["category_num"] = pd.to_numeric(res_inc_df["category_num"], errors="coerce")

In [155]:
#Mapping the values using conditions
def map_category(x):
    if pd.isna(x):
        return "Unknown"
    elif 1 <= x <= 10:
        return "Network Issues"
    elif 11 <= x <= 20:
        return "Database Issues"
    elif 21 <= x <= 30:
        return "Application Errors"
    elif 31 <= x <= 40:
        return "Server Infrastructure"
    elif 41 <= x <= 50:
        return "Integration / API Issues"
    elif 51 <= x <= 60:
        return "Security / Access Issues"
    else:
        return "Monitoring / Alerting"

res_inc_df["category_clean"] = res_inc_df["category_num"].apply(map_category)

In [157]:
res_inc_df["category_clean"].value_counts()

category_clean
Integration / API Issues    6534
Application Errors          5196
Security / Access Issues    4187
Server Infrastructure       4009
Database Issues             1361
Network Issues              1217
Monitoring / Alerting        819
Unknown                       39
Name: count, dtype: int64

In [158]:
res_inc_df= res_inc_df.drop(columns= 'category')
res_inc_df= res_inc_df.drop(columns= 'category_num')
res_inc_df

,incident_id,created_at,resolved_at,severity,team_assigned,resolution_time_hours,root_cause,category_clean
0,INC0000045,2016-02-29 01:16:00,2016-02-29 11:29:00,2 - Medium,Group 56,10.216667,Server Overload,Security / Access Issues
1,INC0000047,2016-02-29 04:40:00,2016-03-01 09:52:00,2 - Medium,Group 24,29.200000,Server Overload,Server Infrastructure
2,INC0000057,2016-02-29 06:10:00,2016-03-01 02:55:00,2 - Medium,Group 70,20.750000,Third-Party Service Failure,Database Issues
3,INC0000060,2016-02-29 06:38:00,2016-03-02 12:06:00,2 - Medium,Group 25,53.466667,Application Bug,Network Issues
4,INC0000062,2016-02-29 06:58:00,2016-02-29 15:51:00,2 - Medium,Group 23,8.883333,API Timeout,Security / Access Issues
...,...,...,...,...,...,...,...,...
23357,INC0118999,2017-02-10 15:55:00,2017-02-10 16:35:00,2 - Medium,Group 53,0.666667,Authentication Failure,Network Issues
23358,INC0119390,2017-02-13 10:33:00,2017-02-14 09:37:00,2 - Medium,Group 39,23.066667,Authentication Failure,Unknown
23359,INC0120304,2017-02-15 02:02:00,2017-02-17 00:47:00,2 - Medium,Group 64,46.750000,Authentication Failure,Security / Access Issues
23360,INC0120835,2017-02-16 09:09:00,2017-02-16 09:53:00,2 - Medium,Group 31,0.733333,Disk Space Issue,Integration / API Issues
23361,INC0121064,2017-02-16 14:17:00,2017-02-16 16:38:00,2 - Medium,Group 31,2.350000,Authentication Failure,Integration / API Issues

In [162]:
#assigning the team based on the category
def assign_team(category):
    
    if category == "Network Issues":
        return "Network Operations Team"
    
    elif category == "Database Issues":
        return "Database Administration Team"
    
    elif category == "Application Errors":
        return "Application Support Team"
    
    elif category == "Server Infrastructure":
        return "Infrastructure Operations Team"
    
    elif category == "Integration / API Issues":
        return "Integration Support Team"
    
    elif category == "Security / Access Issues":
        return "Security Operations Team"
    
    elif category == "Monitoring / Alerting":
        return "Monitoring & DevOps Team"
    
    else:
        return "Service Desk Team"


res_inc_df["assigned_team"] = res_inc_df["category_clean"].apply(assign_team)

In [2]:
res_inc_df= res_inc_df.drop(columns= 'team_assigned')
res_inc_df

NameError: name 'res_inc_df' is not defined

In [1]:
res_inc_df.to_csv("incident_data.csv", index=False)

NameError: name 'res_inc_df' is not defined